AVR_TOOLS_DIR = /usr
ARCHITECTURE = avr
MCU = atmega328p

ARDUINO_DIR = /usr/share/arduino
ARDUINO_LIB_PATH = /usr/share/arduino/lib
ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/libraries
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/variants
BOARDS_TXT = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt

# USER_LIB_PATH = ../lib
# ARDUINO_LIBS = PinChangeInt PID_Beta6 MotorWheel EEPROM
BOARD_TAG    = diecimila

ARDUINO_PORT = /dev/ttyUSB0
CC_NAME = avr-gcc
CXX_NAME = avr-g++
AVRDUDE = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
AVRDUDE_ARD_BAUDRATE = 57600

include /usr/share/arduino/Arduino.mk
